import type { PluralForms } from '../../plural'

export const landing = {
  metaTitle: 'Motion Studio — drag it, tune it, take the code',
  metaDescription:
    'A visual editor over a real React component registry. Tune a component directly, then export the source — React, Next, HTML or JSON. Local-first, no account.',
  ogTitle: 'Motion Studio',
  ogDescription: 'Direct manipulation over real components, with code as the output format.',

  hero: {
    eyebrow: 'Local-first, no account',
    headline: 'Drag it. Tune it. Take the code.',
    subtitle:
      'A visual editor over a real React registry. Export emits the component you were just looking at.',
    openStudio: 'Open the studio',
    tryPlayground: 'Try the playground',
    demoBlock: 'Hero, aurora',
    demoBlockCategory: 'Hero',
    demoSlot: 'Hero slot',
    demoStaticCaption: 'Interactive demo — open the studio',
    /** `{x}` and `{y}` are the dragged block's canvas coordinates. */
    demoLiveCaption: 'x {x}  ·  y {y}  ·  snapping to siblings',
    demoBlockLabel: 'Hero block. Drag it, or move it with the arrow keys.',
    demoPlaced: 'Block placed · the page laid it out at 1280 px',
    demoUndo: 'Undo',
  },

  proof: {
    blocks: 'Blocks',
    presets: 'Motion presets',
    targets: 'Export targets',
    summary: 'Everything below is in the build you can open right now.',
  },

  problem: {
    rail: '01 / gap',
    heading: 'Two kinds of tools, and nothing lives between them.',
    intro:
      'Neither side is bad at its job. The gap is that the job stops halfway across: one hands you a picture of an interface, the other hands you code you cannot try first.',
    designKind: 'Design tools',
    designExamples: 'Figma · Framer · Webflow',
    designCan: 'You drag, you tune, you see it move.',
    designCannot: 'What comes out is a picture or a hosted page. Never code you own.',
    libraryKind: 'Component libraries',
    libraryExamples: 'shadcn/ui · Aceternity · Magic UI',
    libraryCan: 'You get real code, and you keep it.',
    libraryCannot:
      'One hard-coded demo per effect. You cannot try 0.4 damping before you paste it in.',
    conclusionLead: 'The missing tool is the middle:',
    conclusionStrong: 'direct manipulation over real components, with code as the output format.',
  },

  effects: {
    rail: '02 / effects',
    heading: 'Every effect is a component with a schema.',
    intro:
      'Not a snippet to paste and patch. Each one is parameterised, tunable in the inspector, correct under reduced motion, and exportable as source you can read.',
    auroraName: 'Aurora',
    auroraDescription: 'Two-hue blurred fields drifting on unrelated periods behind the content.',
    spotlightName: 'Spotlight',
    spotlightDescription:
      'A soft light that follows the pointer, written from the shared pointer bus.',
    borderBeamName: 'Border beam',
    borderBeamDescription:
      'A lit arc travelling around the node’s own border, masked from a conic gradient.',
    dotGridName: 'Dot grid',
    dotGridDescription: 'A tiled dot lattice, faded at the edges, as surface texture.',
    beamsName: 'Beams',
    beamsDescription: 'Tilted bands of light sweeping across the surface on staggered cycles.',
    particlesName: 'Particles',
    particlesDescription: 'A deterministic field of points drifting upward on their own periods.',
  },

  inspector: {
    rail: '03 / inspector',
    heading: 'Change a value; watch the component, not a preview of one.',
    intro:
      'Controls come from each block’s Zod schema, so a prop that exists has a control and a prop that does not cannot be set. Scrub one and the canvas is already the answer.',
    note: 'One control, two ends of its range. The studio scrubs it with a drag; this page scrubs it with the scroll.',
    before: 'before',
    after: 'after',
    panelTitle: 'Inspector · Style',
    radius: 'Radius',
    glow: 'Glow',
    card: 'Card',
    /** `{percent}` is how far the section has travelled through the viewport. */
    scrollPosition: 'scroll position {percent}%',
  },

  export: {
    rail: '04 / export',
    heading: 'The export is the component you were just looking at.',
    intro:
      'React, Next, plain HTML, JSON, or the theme as tokens. Typed props, hoisted constants, honest class names, and no runtime of ours in the output. This file was generated by the shipped exporter when this page was built.',
    /** `{count}` is the number of files in the sample export. */
    fileCount: { one: '{count} file · react', other: '{count} files · react' } as PluralForms,
  },

  architecture: {
    rail: '05 / shape',
    heading: 'Fifteen packages, one direction.',
    intro:
      'Nothing depends on the app. The editor never imports a block — it talks to the registry through schema types only. That rule is what makes the export testable without a browser.',
    footnote:
      'Read top to bottom: each layer may depend on the ones below it and never on the ones above.',
    appTitle: 'App',
    appNote: 'Next.js 15, App Router',
    appWeb: 'landing · studio · playground · docs',
    editingTitle: 'Editing',
    editingNote: 'One direction of dependency, downward only',
    editingEditor: 'document · commands · history · selection',
    editingCanvas: 'viewport · zoom · pan · snap · guides',
    editingDnd: 'drop rules · reorder · keyboard drag',
    editingCodegen: 'IR · printers · formatter',
    domainTitle: 'Domain',
    domainNote: 'What a document is, and what can go in it',
    domainSchema: 'zod · .motion · migrations',
    domainBlocks: 'the registry · 72 blocks',
    domainMotion: 'presets · springs · scheduler',
    foundationTitle: 'Foundation',
    foundationNote: 'Depended on by everything, depending on nothing',
    foundationChrome: 'chrome · CSS variables',
    foundationShared: 'shared, and small',
  },

  stack: {
    rail: '06 / stack',
    heading: 'The stack, with the actual reasons.',
    introBefore: 'Every one of these is written down at length in',
    introAfter: ', with the alternatives that were rejected and why.',
    next: 'Server Components for the content routes; the studio is one client island in a prerendered shell.',
    typescript:
      '`noUncheckedIndexedAccess` and `exactOptionalPropertyTypes` on. Zero `any` — the document model is the point.',
    zustand:
      'One sliced store. Redux Toolkit is ceremony for a single store, and Immer patches give us history more cheaply.',
    immer:
      'Commands are pure functions on a draft, and the patch pair is the undo entry. 200 steps cost kilobytes.',
    zod: 'One schema per block generates the inspector, validates the file and types the props. Three jobs, one source.',
    tailwind:
      'The exported code has to be Tailwind, so the studio writes what it emits. Tokens generate the `@theme` block.',
    motion:
      'One animation library, no second one. A scroll-scrubbed timeline is a paused CSS animation the shared bus seeks.',
    dndKit:
      'Pointer-based, so keyboard dragging is a first-class path rather than an HTML5 API limitation.',
    codemirror:
      'Monaco is ~2 MB for what is a CSS textarea. Loaded on demand, never in the studio’s first chunk.',
    biome:
      'One tool for lint and format. ESLint plus Prettier is two tools, slower, and twice the configuration.',
    noBackendName: 'No backend',
    noBackend:
      'Local-first. IndexedDB and a file on your disk. No accounts, no telemetry, nothing leaves the browser.',
  },

  cta: {
    heading: 'Open it. Nothing to install, nothing to sign.',
    body: 'The studio runs entirely in this browser. Your documents live in IndexedDB and leave as files you hold.',
    openStudio: 'Open the studio',
    readDocs: 'Read the docs',
  },
}
