import { ImageResponse } from 'next/og'

export const alt = 'Motion Studio — drag it, tune it, take the code'

export const size = { width: 1200, height: 630 }

export const contentType = 'image/png'

/**
 * Generated by `next/og` at build time — PERFORMANCE.md § Images. The values are literals rather than
 * `var(--ms-color-*)`: Satori resolves no cascade and no custom properties, so a token reference here
 * would render as transparent. These are `studioDark`'s surface-0, accent and foreground, and the
 * comment is the link between them.
 */
export default function OpengraphImage() {
  return new ImageResponse(
    <div
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        padding: 72,
        background: '#0b0b0f',
        backgroundImage:
          'radial-gradient(900px 520px at 15% -10%, rgba(124,106,247,0.35), transparent 70%), radial-gradient(700px 420px at 90% 15%, rgba(56,132,255,0.22), transparent 70%)',
        color: '#f5f5f7',
        fontSize: 32,
      }}
    >
      <div
        style={{
          display: 'flex',
          fontSize: 22,
          letterSpacing: 4,
          textTransform: 'uppercase',
          color: '#9d9daa',
        }}
      >
        Motion Studio
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
        <div style={{ display: 'flex', fontSize: 84, lineHeight: 1, letterSpacing: -2 }}>
          Drag it. Tune it. Take the code.
        </div>
        <div style={{ display: 'flex', fontSize: 30, color: '#9d9daa', maxWidth: 900 }}>
          A visual editor over a real React component registry.
        </div>
      </div>

      <div style={{ display: 'flex', gap: 40, fontSize: 22, color: '#9d9daa', letterSpacing: 2 }}>
        <div style={{ display: 'flex' }}>72 blocks</div>
        <div style={{ display: 'flex' }}>51 motion presets</div>
        <div style={{ display: 'flex' }}>4 export targets</div>
      </div>
    </div>,
    size,
  )
}
