import { SectionIntro } from './section-intro'
import { Section } from './section-rail'

import {
  EXPORT_SAMPLE_FILES,
  EXPORT_SAMPLE_LINES,
  EXPORT_SAMPLE_PATH,
} from './generated/export-sample'

/** The five colours ADR-124 settled on, as token-backed classes. `plain` inherits and needs none. */
const TOKEN_CLASS: Readonly<Record<string, string>> = {
  comment: 'text-foreground-muted',
  string: 'text-success',
  number: 'text-info',
  keyword: 'text-accent',
  plain: '',
}

/**
 * The code that comes out — generated at build time by our own exporter and tokenised there too
 * (ADR-293). Nothing here is written by hand, which is the section's whole claim: the page cannot
 * show code the exporter would not produce, because it did not have the option.
 *
 * No typing animation. `prompts/51` suggests one, and a marketing page that withholds the code it is
 * bragging about until an animation finishes is the opposite of the argument — the reveal is that the
 * file is *already there*, complete, syntax-correct and four files long.
 */
export function ExportReveal() {
  return (
    <Section id="export" label="04 / export">
      <div className="flex flex-col gap-10 py-16 lg:py-24">
        <SectionIntro
          heading="The export is the component you were just looking at."
          id="export-heading"
        >
          React, Next, plain HTML or JSON. Typed props, hoisted constants, honest class names, and
          no runtime of ours in the output. This file was generated by the shipped exporter when
          this page was built.
        </SectionIntro>

        <figure className="m-0 overflow-hidden rounded-xl border border-border bg-surface-1">
          <figcaption className="flex flex-wrap items-center gap-x-4 gap-y-1 border-border-subtle border-b px-4 py-2.5">
            <span className="font-mono text-2xs uppercase tracking-[0.14em]" id="export-file">
              {EXPORT_SAMPLE_PATH}
            </span>
            <span className="font-mono text-2xs text-foreground-muted uppercase tracking-[0.14em]">
              {EXPORT_SAMPLE_FILES.length} files · react
            </span>
          </figcaption>

          {/*
            ACCESSIBILITY.md § Dialogs already settles the shape of a code block that scrolls:
            `tabindex="0"`, a role and a label. It is stated there for the export dialog and it holds
            wherever a `pre` scrolls — at 320 px this one does, and without the tab stop the right
            half of every line is unreachable from the keyboard (ADR-298).

            The ring is drawn inside the box because the figure clips it: an outer ring on an element
            that fills a container with `overflow-hidden` is a focus indicator nobody sees.
          */}
          <pre
            aria-labelledby="export-file"
            className="overflow-x-auto px-4 py-4 font-mono text-2xs leading-[1.7] focus-visible:-outline-offset-2 focus-visible:outline-2 focus-visible:outline-accent-ring sm:text-xs"
            // biome-ignore lint/a11y/useSemanticElements: <section> cannot replace <pre> — the white-space handling is what makes the sample readable
            role="region"
            // biome-ignore lint/a11y/noNoninteractiveTabindex: a region that scrolls has to be focusable, or the part of the file past the right edge is unreachable
            tabIndex={0}
          >
            <code>
              {EXPORT_SAMPLE_LINES.map((line, index) => (
                // biome-ignore lint/suspicious/noArrayIndexKey: a file's lines are identified by their number
                <span className="block" key={index}>
                  {line.length === 0
                    ? ' '
                    : line.map((token, position) => (
                        <span
                          className={TOKEN_CLASS[token[0]] ?? ''}
                          // biome-ignore lint/suspicious/noArrayIndexKey: tokens are a fixed sequence within a line
                          key={position}
                        >
                          {token[1]}
                        </span>
                      ))}
                </span>
              ))}
            </code>
          </pre>
        </figure>
      </div>
    </Section>
  )
}
