#!/usr/bin/env tsx
/**
 * The code the landing page shows, generated by the exporter that ships — `prompts/51`: "Generating
 * it at build time means the landing page cannot show code the exporter would not actually produce."
 *
 * It builds a small document from the real catalogue, runs `buildIR` → `printReact` → Prettier, and
 * writes the chosen file as pre-tokenised lines. The page renders spans; it loads no highlighter and
 * no grammar, which is the "zero runtime cost" the prompt asks for — ADR-293 records why the
 * tokeniser is ours rather than Shiki.
 *
 * Run with `pnpm generate:landing`. The output is committed.
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { tokenize } from '@motion-studio/blocks/highlight'
import { markupRegistry } from '@motion-studio/blocks/markup'
import { blockRegistry } from '@motion-studio/blocks/registry'
import { buildIR, formatFiles, printReact, resolveOptions } from '@motion-studio/codegen'
import { presetRegistry } from '@motion-studio/motion'
import {
  COLOR_MODE_SCRIPT,
  COLOR_MODE_STORAGE_KEY,
  TOKEN_FORMATS,
  resolveForExport,
  toCssVariables,
} from '@motion-studio/theme'

import { builder, place, templateDocument } from './templates/builder'

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'apps',
  'web',
  'src',
  'components',
  'landing',
  'generated',
  'export-sample.ts',
)

/** The file the page shows, and how much of it fits on a marketing page without an ellipsis. */
const WANTED = 'hero-aurora.tsx'
const MAX_LINES = 26

/** One hero, with the copy the landing page's own hero uses, so the sample is of *this* page. */
const sample = (): ReturnType<typeof templateDocument> => {
  const page = builder()
  const root = place(page, 'container', null, 'root')

  place(page, 'hero-aurora', root, 'children', {
    eyebrow: 'Motion Studio',
    headline: 'Drag it. Tune it. Take the code.',
    subtitle:
      'An infinite canvas over a real component registry, and an export that reads like it was written by hand.',
  })

  return templateDocument('Landing sample', 'landingsample', page.nodes)
}

const document = sample()
const theme = resolveForExport(document.theme)
const options = resolveOptions({ target: 'react' })

const ir = buildIR({
  document,
  registry: blockRegistry,
  presets: presetRegistry,
  markup: markupRegistry,
  options,
})

const printed = printReact({
  ir,
  options,
  theme: {
    css: toCssVariables(theme),
    colorModeScript: COLOR_MODE_SCRIPT,
    colorModeStorageKey: COLOR_MODE_STORAGE_KEY,
    tokens: TOKEN_FORMATS.map((format) => ({
      id: format.id,
      filename: format.filename,
      contents: format.print(theme),
    })),
  },
})

const formatted = await formatFiles(printed.files)
const file =
  formatted.files.find((entry) => entry.path === WANTED) ??
  formatted.files.find((entry) => entry.path.endsWith('.tsx'))

if (file === undefined) {
  throw new Error(`the export produced no .tsx file; it produced ${formatted.files.length}`)
}

const lines = file.contents
  .split('\n')
  .slice(0, MAX_LINES)
  .map((line) => tokenize(line, 'tsx').map((token) => [token.kind, token.text] as const))

const body = `/*
 * Generated by \`pnpm generate:landing\`. Do not edit.
 *
 * These are the bytes ${JSON.stringify(file.path)} came out of the exporter as, tokenised at build
 * time — the landing page ships spans, not a highlighter.
 */
import type { TokenKind } from '@motion-studio/blocks/highlight'

export const EXPORT_SAMPLE_PATH = ${JSON.stringify(file.path)}

export const EXPORT_SAMPLE_FILES = ${JSON.stringify(
  formatted.files.map((entry) => entry.path),
  null,
  2,
)} as const

export const EXPORT_SAMPLE_LINES: readonly (readonly (readonly [TokenKind, string])[])[] =
  ${JSON.stringify(lines, null, 2)}
`

writeFileSync(OUT, body)

console.log(
  `Wrote ${lines.length} lines of ${file.path} (${formatted.files.length} files in the export) to ${OUT}`,
)
